### ISSUE TITLE
RB1, RB2 crash on start, RB3 is okay probably

### ISSUE THREAD

**Issue by nrsolo** [tlaik/neptastic#3] opened 2021-07-26 07:12 UTC
1. Extracted v1.1.3 files to game directories
2. Launched RB1, RB2
3. Black game window
4. "Sorry! Application has crashed"

Removing the files restores game functionality

RB3 launches fine but I did not check if the mod was working

AMD 5600X
RTX 3070

**Comment by tlaik** [comment] 2021-07-26 08:55
Which mod version were you using? Can you check if 1.0.0 and 1.1.0 both crash for you?

**Comment by nrsolo** [comment] 2021-07-26 09:03
This was on v1.1.3

Using the same installation method:
v.1.1.2 and v.1.1.0 also crashes RB1 and RB2
v.1.0.0, not compatible with RB1

I made a Birth2 folder in RB2-- I read somewhere that this method started with RB2. Launches fine if the files are in a Birth2 folder, but did not check to see if was working.

**Comment by tlaik** [comment] 2021-07-26 10:38
1.0.0 is compatible with RB2 and RB3 only. I'd like to know if at least this first version works with RB2 for you.

Making a Birth3 folder for mod files is only necessary for RB3 because of **;** in the file path. I pointed this out in the installation instructions. In fact, if you make Birth1/Birth2 folders for RB1/RB2, those games simply won't pick up the mod.

It is quite possible that the problem is with insufficient memory and/or game not using it well. Try setting shadow quality in the nep.ini to 2.0 or even 1.0 and see if the mod starts working.

**Comment by nrsolo** [comment] 2021-07-26 11:08
Currently all versions of the mod crash RB1 and RB2 on startup when placed in the game folder, even with shadows set to 1.0. Only exception is RB3 when placed directly in the game folder and not in a Birth3 folder.

**Comment by tlaik** [comment] 2021-07-26 11:41
Did you try using old Hyperresolution Neptunia plugin before, does it work or crash the same way?
https://github.com/PeterTh/neptunia_hyperres

Also, if there's something in nep.log, please upload it to https://pastebin.com

**Comment by nrsolo** [comment] 2021-07-26 12:05
I have installed Hyperresolution on RB1 and it does not crash the game on start and I am able to play. I'm unable to discern if its working, however.

RB1 nep.log https://pastebin.com/3Wi2rQbm
RB2 nep.log https://pastebin.com/nuyFFttA

**Comment by tlaik** [comment] 2021-07-26 12:39
It's important to know if either mod is actually activated when you're testing them.
Here are more detailed instructions on Hyperresolution: https://community.pcgamingwiki.com/files/file/555-hyperresolution-neptunia/

To make sure that you'll notice the effect if the mod is loading, set "renderWidth" and "renderHeight" to something low, like 640 and 360. If the picture isn't heavily pixelated with these settings, the mod isn't working.

Also, I've noticed in the log that your shadows are still being set to 4096x4096 (which is default quality 4.0 setting).
After testing Hyperresolution, test the Neptastic mod again with the following settings: https://pastebin.com/K3dqWSmb

**Comment by nrsolo** [comment] 2021-07-26 12:48
Hyperresolution is indeed working when a lower resolution is set.

Using your provided settings with 1.0 shadows and 1/4 resolution scaling, the game still crashes on launch. https://pastebin.com/G9KP5v4f

**Comment by tlaik** [comment] 2021-07-26 14:22
Made a version with far more logging, hopefully this will let us pin down the moment of crash better. Otherwise it's identical to v1.1.3, try it out.
https://github.com/tlaik/neptastic/releases/tag/v1.1.3-test.1

It'll generate quite a bit log, consider zipping it, uploading somewhere and posting a link here.

**Comment by nrsolo** [comment] 2021-07-26 14:32
Output of v.1.1.3-test.1 nep.log with logging level 4 https://pastebin.com/GPtXKFw1

**Comment by tlaik** [comment] 2021-07-26 21:39
I added several hard switches to enable or disable mod functionality, please try to see what works and what doesn't work for you. Perhaps you can start with everything (including FPS unlock) set to "No".
https://github.com/tlaik/neptastic/releases/tag/v1.1.3-test.2

**Comment by nrsolo** [comment] 2021-07-26 21:48
Unfortunately the game still crashes on load even with all switches set to "No" in RB1 and RB2. 
Log: https://pastebin.com/ZwuQgEXW
I appreciate the effort though

**Comment by nrsolo** [comment] 2021-07-26 21:57
Additionally, I have installed the game and test.2 mod on a separate system (i5-8250U, GTX 1050) and the same crash occurs with all switches disabled

**Comment by tlaik** [comment] 2021-07-26 22:49
There's something strange, the line **[I]: Preallocating 157286400 bytes @ 0x04b43020** in your log shouldn't occur if memory optimizations are turned off.
Also, I've had someone with GoG version running into more troubles (including without mod) than with Steam version.
Honestly, first time I see the mod crashing this reliably for anyone. Re-check that you disabled everything (Your log also shows **[I]: FPS unlocked**, which shouldn't appear either, if FPS unlock is disabled in the nep.ini), but, otherwise, I'm running out of ideas.

**Comment by nrsolo** [comment] 2021-07-27 09:57
Sorry I missed the FPS unlock switch up top. That definitely is the issue

test.2: RB1 now launches correctly with FPS Unlock disabled and everything else off. It also launches with everything enabled and FPS Unlock off.

v1.1.3: RB1 works and mod is active with FPS Unlock disabled, Shadows at 8x, Resolution scale at 2x, all else unchanged. Shadow resolution working correctly and textures look good.

_Unlimited_ FPS unlock seems to be the problem, maybe the game engine just can't handle it properly, which is strange since I don't think RB3 is significantly different and that launches fine with everything on-- Maybe a workaround would be to FPS cap at a higher rate like 120 or 240. It's completely fine with 60 though

**Comment by tlaik** [comment] 2021-07-27 11:44
Very interesting. So, which version of the game are you using, Steam or GoG?
Also, can you check the exact size (Right-click -> Properties -> Size on disk) of **NeptuniaReBirth1.exe** in your game directory? My Steam version right now is at 5,436,928 bytes. It might be the case that we're dealing with different game builds, and that's something FPS unlock relies on.
In the meantime, you can keep playing using the version of the mod you got right now, just switch the log level to 3 or below so it doesn't create gigabytes worth of logging.

**Comment by nrsolo** [comment] 2021-07-27 12:15
Steam
size: 5,436,928 b
size on disk: 5,439,488 b

**Comment by tlaik** [comment] 2021-07-28 12:05
Added another way for FPS unlock to find the code it needs, and also an early exit without crash in case it still can't do so. Try it out:
https://github.com/tlaik/neptastic/releases/tag/v1.1.3-test.3

**Comment by nrsolo** [comment] 2021-07-28 13:54
test.3 tested and working on RB1 with resolution at 2x, shadows 8x, FPS unlocked, all features enabled. https://pastebin.com/h0PgBhSa
Greatly appreciated

The FPS addresses in lines 5 and 6 are consistent through multiple launches

**Comment by tlaik** [comment] 2021-07-28 16:22
That's good to hear; but the cause of it is still interesting. The first method seemed to work for everyone else so far... Do you have an antivirus running, or some in-game overlay (other than Steam overlay)? Perhaps some other tools to change performance or visuals in your games?

**Comment by nrsolo** [comment] 2021-07-28 16:28
No antivirus other than Windows Defender. The only other overlay I usually have is Shadowplay/GeForce Experience but it does not appear on these games. No other visual or game mods are installed

**Comment by tlaik** [comment] 2021-07-28 22:56
Thanks for your help with testing everything, the fix has been merged into version 1.1.4:
https://github.com/tlaik/neptastic/releases/tag/v1.1.4

**Closed as completed** 2021-07-29 08:33 UTC
Labels: bug
